const DestinationDetails = [
    {
      id: 1,
      Places: "Jodhpur",
      Cost_for_a_Nomad: 450,
      Wifi_Mbps: 90,
      Fun: 5,
      Air_Quality_AQI: 150,
      Safety: 4,
      Electricity: 3,
      Nightlife: 3,
      Place_for_WFH: 3,
      Avg_Trip_time_days: 3,
      Safe_for_Women: 3,
      Climate: "Warm",
      Medical: 4
    },
    {
      id: 2,
      Places: "Goa",
      Cost_for_a_Nomad: 1200,
      Wifi_Mbps: 130,
      Fun: 5,
      Air_Quality_AQI: 120,
      Safety: 4,
      Electricity: 3,
      Nightlife: 5,
      Place_for_WFH: 5,
      Avg_Trip_time_days: 12,
      Safe_for_Women: 4,
      Climate: "Warm",
      Medical: 4
    },
    {
      id: 3,
      Places: "Jaipur",
      Cost_for_a_Nomad: 600,
      Wifi_Mbps: 20,
      Fun: 3,
      Air_Quality_AQI: 120,
      Safety: 4,
      Electricity: 4,
      Nightlife: 5,
      Place_for_WFH: 5,
      Avg_Trip_time_days: 4,
      Safe_for_Women: 4,
      Climate: "Warm",
      Medical: 5
    },
    {
      id: 4,
      Places: "Mysore",
      Cost_for_a_Nomad: 600,
      Wifi_Mbps: 20,
      Fun: 3,
      Air_Quality_AQI: 60,
      Safety: 4,
      Electricity: 3,
      Nightlife: 4,
      Place_for_WFH: 5,
      Avg_Trip_time_days: 14,
      Safe_for_Women: 4,
      Climate: "Warm",
      Medical: 4
    },
    {
      id: 5,
      Places: "Chandigarh",
      Cost_for_a_Nomad: 700,
      Wifi_Mbps: 20,
      Fun: 3,
      Air_Quality_AQI: 150,
      Safety: 4,
      Electricity: 4,
      Nightlife: 5,
      Place_for_WFH: 5,
      Avg_Trip_time_days: 3,
      Safe_for_Women: 5,
      Climate: "Cold",
      Medical: 5
    },
    {
      id: 6,
      Places: "McLeod Ganj",
      Cost_for_a_Nomad: 1200,
      Wifi_Mbps: 40,
      Fun: 2,
      Air_Quality_AQI: 180,
      Safety: 4,
      Electricity: 3,
      Nightlife: 3,
      Place_for_WFH: 5,
      Avg_Trip_time_days: 14,
      Safe_for_Women: 4,
      Climate: "Cold",
      Medical: 3
    },
    {
      id: 7,
      Places: "Srinagar",
      Cost_for_a_Nomad: 500,
      Wifi_Mbps: 20,
      Fun: 2,
      Air_Quality_AQI: 90,
      Safety: 4,
      Electricity: 3,
      Nightlife: 3,
      Place_for_WFH: 2,
      Avg_Trip_time_days: 11,
      Safe_for_Women: 3,
      Climate: "Cold",
      Medical: 3
    },
    {
      id: 8,
      Places: "Rishikesh",
      Cost_for_a_Nomad: 700,
      Wifi_Mbps: 20,
      Fun: 2,
      Air_Quality_AQI: 180,
      Safety: 4,
      Electricity: 3,
      Nightlife: 3,
      Place_for_WFH: 5,
      Avg_Trip_time_days: 14,
      Safe_for_Women: 3,
      Climate: "Warm",
      Medical: 3
    },
    {
      id: 9,
      Places: "Guwahati",
      Cost_for_a_Nomad: 500,
      Wifi_Mbps: 20,
      Fun: 3,
      Air_Quality_AQI: 170,
      Safety: 4,
      Electricity: 3,
      Nightlife: 3,
      Place_for_WFH: 5,
      Avg_Trip_time_days: 6,
      Safe_for_Women: 4,
      Climate: "Warm",
      Medical: 4
    },
    {
      id: 10,
      Places: "Delhi",
      Cost_for_a_Nomad: 700,
      Wifi_Mbps: 40,
      Fun: 4,
      Air_Quality_AQI: 150,
      Safety: 3,
      Electricity: 3,
      Nightlife: 5,
      Place_for_WFH: 3,
      Avg_Trip_time_days: 4,
      Safe_for_Women: 3,
      Climate: "Warm",
      Medical: 5
    },
    {
      id: 11,
      Places: "Mumbai",
      Cost_for_a_Nomad: 950,
      Wifi_Mbps: 20,
      Fun: 4,
      Air_Quality_AQI: 100,
      Safety: 4,
      Electricity: 3,
      Nightlife: 5,
      Place_for_WFH: 4,
      Avg_Trip_time_days: 5,
      Safe_for_Women: 3,
      Climate: "Warm",
      Medical: 5
    }
  ];
  
  export default DestinationDetails;
  